version: '3'

services:
  web:
    logging:
      options:
        max-size: 50m
    build: '.'
    init: true
    env_file:
      - '.env'
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - '.:/app'
      - '~/.ssh:/home/root/.ssh'
    entrypoint: ["script/_entrypoint.sh"]
    environment:
      NLS_LANG: "AMERICAN_AMERICA.WE8ISO8859P1"
    command: ./script/_server
