version: '3'

services:
  web:
    logging:
      options:
        max-size: 50m
    build: '.'
    env_file:
      - '.env'
    ports:
      - 3000:3000
    volumes:
      - '.:/app'
      - '~/.ssh:/home/root/.ssh'
    entrypoint: ["script/_entrypoint.sh"]
    command: './script/_web_container_setup && ./script/_server'
