servers:
  web:
    hosts:
      - asr-container-tst-web-public-01.oit.umn.edu
    labels:
      traefik.http.routers.course-fees-web.rule: Host(`course-fees-staging.umn.edu`) || Host(`course-fees.asr-container-tst-web-public-01.asr.umn.edu`)

env:
  clear:
    RAILS_ENV: "staging"

logging:
  driver: journald
  options:
    tag: "course-fees-web-staging"
