#!/bin/sh

# script/deploy: Deploy the application
#   change the url opened at the end of the script to the URL of the application, if applicable


set -e

cd "$(dirname "$0")/.."

eval `ssh-agent -s`
ssh-add /home/root/.ssh/id_rsa

if [ -n "$1" ]; then
  echo "===> Deploying to $1"
  bundle exec cap "$1" deploy
else
  echo "===> Deploying to staging"
  bundle exec cap staging deploy
fi
