#!/bin/bash

# script/_server: Starts a Rails server in the container

set -e

cd "$(dirname "$0")/.."

./script/_update

test -z "$RACK_ENV" &&
  RACK_ENV='development'

# boot the app and any other necessary processes.
RAILS_ENV=development bin/rails s -b 0.0.0.0
