#!/bin/sh

# script/_setup: Logs the user into LastPass and calls the lastpassify binstub
# to set up DB credentials

set -e

cd "$(dirname "$0")/.."

echo "===> Getting passwords from LastPass if available"
DEV_USER=$1
lpass login $DEV_USER@umn.edu
./bin/lastpassify

echo "==> App is now ready to go!"
