#!/bin/sh

# script/lint: Run our code and security linters

set -e

cd "$(dirname "$0")/.."

echo "==> Running Standard..."
docker compose exec -T web bin/standardrb --no-fix

echo "==> Checking Gems..."
docker compose exec -T web bin/bundle-audit check --update

echo "==> Running Brakeman..."
docker compose exec -T web bin/brakeman
