#!/bin/sh

# script/_setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

docker compose build

script/bootstrap

echo "==> Running lpassify"
  docker run \
    -it --rm \
    -e LASTPASS_USERNAME=$(whoami) \
    -v "$(pwd):/workdir" \
    --pull=always \
    asrcustomsolutions/lastpass:latest \
    lastpassify

echo "==> App is now ready to go!"
