#!/bin/sh

# script/_setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

docker compose build

script/bootstrap

docker compose run web script/_setup $(whoami)

echo "==> App is now ready to go!"
