#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.


set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x


if [ -n "$1" ]; then
  # pass arguments to test call. This is useful for calling a single test.
  docker-compose exec web script/_test "$1"
else
  docker compose exec web script/_test
fi
